import { Container, Title } from "@mantine/core";
import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <Container>
      <Head>
        <title>Interactive IQRA</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>This is going to be a long journey</Title>
    </Container>
  );
}
