import {
  SignInButton,
  SignOutButton,
  UserButton,
  useSession,
} from "@clerk/nextjs";
import { Button, Container } from "@mantine/core";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const { session } = useSession();
  const { data } = api.post.hello.useQuery({ text: "Helo" });

  if (!data) return <div>Loading...</div>;

  const { greeting } = data;
  console.log(greeting);

  return (
    <Container>
      <SignInButton>
        <Button>Sign In</Button>
      </SignInButton>
      <SignOutButton>
        <Button>OUT</Button>
      </SignOutButton>
      <Head>
        <title>Interactive IQRA</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Title>Your Identity: {greeting}</Title> */}
      <UserButton />
    </Container>
  );
}
